# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bygglistan
email: info@beckmancreative.se
description: > # this means to ignore newlines until "baseurl:"
 Bygglistan är en samling länkar av utvalda tillverkare och leverantörer
 av produkter för byggprojekt. Helt gratis och tokigt lättanvänd.
 En present från Beckman Creative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bygglistan.com" # the base hostname & protocol for your site
twitter_username: pbeck
github_username:  pbeck

# Build settings
markdown: kramdown
